accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('sign-up/', views.sign_up, name='sign_up'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

heestagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/edit/', views.edit, name='edit'),
    path('<int:post_id>/update/', views.update, name='update'),
    path('<int:post_id>/delete/', views.delete, name='delete'),
    path('<int:post_id>/like/', views.like, name='like'),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    body = models.TextField()
    image = models.ImageField(upload_to='posts', null=True)
    created_at = models.DateTimeField()
    liked_users = models.ManyToManyField(User, related_name='liked_posts')

    def __str__(self):
        if self.user:
            return f'{self.user.get_username()}: {self.body}'
        else:
            return f'{self.body}'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.
def sign_up(request):
    context = {}

    if request.method == 'POST':
        if (request.POST.get('username') and
            request.POST.get('password') and
            request.POST.get('password') == request.POST.get('password_check')):

            new_user = User.objects.create_user(
                username = request.POST.get('username'),
                password = request.POST.get('password'),
            )

            auth.login(request, new_user)
            return redirect('posts:index')

        else:
            context['error'] = '아이디와 비밀번호를 다시 확인해주세요.'

    return render(request, 'accounts/sign_up.html', context)


def login(request):
    context = {}

    if request.method == 'POST':
        if request.POST.get('username') and request.POST.get('password'):

            user = auth.authenticate(
                request,
                username = request.POST.get('username'),
                password = request.POST.get('password'),
            )

            if user is not None:
                auth.login(request, user)
                return redirect('posts:index')
            else:
                context['error'] = '아이디와 비밀번호를 다시 확인해주세요.'

        else:
            context['error'] = '아이디와 비밀번호를 모두 입력해주세요.'    

    return render(request, 'accounts/login.html', context)


def logout(request):
    if request.method == 'POST':
        auth.logout(request)

    return redirect('posts:index')    

posts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Post
from django.utils import timezone
from django.contrib.auth.decorators import login_required
import requests


# Create your views here.
def index(request):
    dog_api_response = requests.get('https://dog.ceo/api/breeds/image/random')
    dog_api_response_dictionary = dog_api_response.json()
    dog = None
    if dog_api_response_dictionary.get('status') == 'success':
        dog = dog_api_response_dictionary.get('message')    

    posts = Post.objects.all()
    context = {'posts': posts, 'dog': dog}

    return render(request, 'posts/index.html', context)

def detail(request, post_id):
    post = Post.objects.get(id=post_id)
    context = {'post': post}

    return render(request, 'posts/detail.html', context)

@login_required
def new(request):
    return render(request, 'posts/new.html')


@login_required
def create(request):
    user = request.user
    body = request.POST.get('body')
    image = request.FILES.get('image')

    post = Post(user=user, body=body, image=image, created_at=timezone.now())
    post.save()

    return redirect('posts:detail', post_id=post.id)


@login_required
def edit(request, post_id):
    try:
        post = Post.objects.get(id=post_id, user=request.user)
    except Post.DoesNotExist:
        return redirect('posts:index')
    
    context = {'post': post}

    return render(request, 'posts/edit.html', context)


@login_required
def update(request, post_id):
    try:
        post = Post.objects.get(id=post_id, user=request.user)
    except Post.DoesNotExist:
        return redirect('posts:index')

    post.body = request.POST.get('body')
    image = request.FILES.get('image')
    if image:
        post.image = image

    post.save()

    return redirect('posts:detail', post_id=post.id)


@login_required
def delete(request, post_id):
    try:
        post = Post.objects.get(id=post_id, user=request.user)
    except Post.DoesNotExist:
        return redirect('posts:index')

    post.delete()

    return redirect('posts:index')


@login_required
def like(request, post_id):
    if request.method == 'POST':
        try:
            post = Post.objects.get(id=post_id)

            if request.user in post.liked_users.all():
                post.liked_users.remove(request.user)
            else:
                post.liked_users.add(request.user)

            return redirect('posts:detail', post_id=post.id)

        except Post.DoesNotExist:
            pass   

    return redirect('posts:index')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    {% if error %}
      <div class="alert alert-danger mt-3">
        {{ error }}
      </div>
    {% endif %}

    <h1>Login</h1>

    <form method="POST" action="{% url 'accounts:login' %}"> 
      {% csrf_token %}
       
      <div class="mb-3 col-md-6">
        <label class="form-label" for="username">아이디</label>
        <input class="form-control" id="username" type="text" name="username" placeholder="아이디">
      </div>
  
      <div class="mb-3 col-md-6">
        <label class="form-label" for="password">비밀번호</label>
        <input class="form-control" id="password" type="password" name="password" placeholder="비밀번호">
      </div>
      
      <div class="mb-3">
        <button type="submit" class="btn btn-primary">로그인</button>
      </div>      
    </form>
  </div>
{% endblock %}

accounts/templates/accounts/sign_up.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    {% if error %}
      <div class="alert alert-danger mt-3">
        {{ error }}
      </div>
    {% endif %}

    <h1>Sign Up</h1>

    <form method="POST" action="{% url 'accounts:sign_up' %}"> 
      {% csrf_token %}

      <div class="mb-3 col-md-6">
        <label class="form-label" for="username">아이디</label>
        <input class="form-control" id="username" type="text" name="username" placeholder="아이디">
      </div>
  
      <div class="mb-3 col-md-6">
        <label class="form-label" for="password">비밀번호</label>
        <input class="form-control" id="password" type="password" name="password" placeholder="비밀번호">
      </div>
      
      <div class="mb-3 col-md-6">
        <label class="form-label" for="password_check">비밀번호 확인</label>
        <input class="form-control" id="password_check" type="password" name="password_check" placeholder="비밀번호 확인">
      </div>      
      
      <div class="mb-3">
        <button type="submit" class="btn btn-primary">회원가입</button>
      </div>      
    </form>
  </div>
{% endblock %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'posts/style.css' %}">
{% endblock %}

{% block content %}
  <div class="container">
    <h1>Post Detail</h1>

    {% if post.image %}
      <div class="mb-3 col-md-6">
        <img class="img-fluid" src="{{ post.image.url }}" alt="Post Image">
      </div>    
    {% endif %}    

    <div class="mb-3 col-md-6">
      <label class="form-label" for="author">작성자</label>
      <input readonly class="form-control-plaintext" id="author" type="text" name="author" value="{{ post.user.get_username }}">
    </div>

    <div class="mb-3 col-md-6">
      <label class="form-label" for="body">본문</label>
      <textarea readonly class="form-control-plaintext" id="body" cols="30" rows="10" name="body">{{ post.body }}</textarea>
    </div>         

    <div class="mb-3 col-md-6">
      {{ post.created_at }}
    </div>    

    <div class="mb-3 col-md-6">
      좋아요 수: {{ post.liked_users.count }}
    </div>    

    {% if user.is_authenticated %}
      <form class="mb-3" method="POST" action="{% url 'posts:like' post.id %}">
        {% csrf_token %}

        {% if user in post.liked_users.all %}
          <button type="submit" class="btn btn-primary">LIKE</button>
        {% else %}
          <button type="submit" class="btn btn-secondary">LIKE</button>
        {% endif %}
      </form> 
    {% endif %}    
  
    <a href="{% url 'posts:index' %}">목록</a>
    {% if user == post.user %}
      <a href="{% url 'posts:edit' post.id %}">수정하기</a>
      <a href="{% url 'posts:delete' post.id %}">삭제하기</a>    
    {% endif %}
  </div>
{% endblock %}

posts/templates/posts/edit.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'posts/style.css' %}">
{% endblock %}

{% block content %}
  <div class="container">
    <h1>Edit Post</h1>

    {% if post.image %}
      <div class="mb-3 col-md-6">
        <img class="img-fluid" src="{{ post.image.url }}" alt="Post Image">
      </div>    
    {% endif %}    

    <form method="POST" action="{% url 'posts:update' post.id %}" enctype="multipart/form-data">
      {% csrf_token %}
  
      <div class="mb-3 col-md-6">
        <label class="form-label" for="body">본문</label>
        <textarea class="form-control" id="body" cols="30" rows="10" name="body">{{ post.body }}</textarea>
      </div>

      <div class="mb-3 col-md-6">
        <label class="form-label" for="image">이미지</label>
        <input type="file" class="form-control" id="image" name="image">
      </div>      
  
      <div class="mb-3">
        <button type="submit" class="btn btn-primary">수정하기</button>
      </div>      
    </form>
  
    <a href="{% url 'posts:index' %}">목록</a>  
  </div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'posts/style.css' %}">
{% endblock %}

{% block content %}
  <div class="container">
    <h1>Posts</h1>

    {% if posts %}
      <table class="table">
        <thead class="table-dark">
          <tr>
            <th>#</th>
            <th>작성자</th>
            <th>본문</th>
            <th>게시일</th>
            <th>상세</th>
          </tr>
        </thead>
        <tbody>
          {% for post in posts %}
            <tr>
              <td>{{ post.id }}</td>
              <td>{{ post.user.get_username }}</td>
              <td>{{ post.body }}</td>
              <td>{{ post.created_at }}</td>
              <td><a href="{% url 'posts:detail' post.id %}">보기</a></td>
            </tr>
          {% endfor %}        
        </tbody>
      </table>
    {% else %}
      <p>No Post</p>
    {% endif %}
  
    <a href="/posts/new">글쓰기</a>
    
    {% if dog %}
      <div class="card mt-3">
        <div class="row g-0">
          <div class="col-md-4">
            <img class="card-img" src="{{ dog }}" alt="Dog Image">
          </div>
          <div class="col-md-8 card-body">
            <h5 class="card-title">강아지를 보고 싶다면?</h5>
              <p class="card-text">Dog API를 사용합시다.</p>
              <a href="https://dog.ceo/dog-api/" class="card-link" target="_blank">Dog API</a>
          </div>
        </div>
      </div>
    {% endif %}    
  </div>
{% endblock %}

posts/templates/posts/new.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'posts/style.css' %}">
{% endblock %}

{% block content %}
  <div class="container">
    <h1>New Post</h1>

    <form method="POST" action="{% url 'posts:create' %}" enctype="multipart/form-data">
      {% csrf_token %}
  
      <div class="mb-3 col-md-6">
        <label class="form-label" for="body">본문</label>
        <textarea class="form-control" id="body" cols="30" rows="10" name="body"></textarea>
      </div>

      <div class="mb-3 col-md-6">
        <label class="form-label" for="image">이미지</label>
        <input type="file" class="form-control" id="image" name="image">
      </div>      
  
      <div class="mb-3">
        <button type="submit" class="btn btn-primary">작성하기</button>
      </div>      
    </form>
  
    <a href="{% url 'posts:index' %}">목록</a>  
  </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  {% block style %}
  {% endblock %}
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Heestagram</title>
</head>
<body>
  <div class="container pt-3">
    {% if user.is_authenticated %}
      <form method="POST" action="{% url 'accounts:logout' %}">
        {% csrf_token %}
  
        {{ user.get_username }} 님 환영합니다.
        <button type="submit" class="btn btn-primary ms-3">LOGOUT</button>
      </form>
    {% else %}
      <a class="text-decoration-none" href="{% url 'accounts:login' %}">
        <button class="btn btn-primary">LOGIN</button>
      </a>
      <a class="text-decoration-none" href="{% url 'accounts:sign_up' %}">
        <button class="btn btn-primary ms-3">SIGN UP</button>
      </a>      
    {% endif %}
  </div>

  {% block content %}
  {% endblock %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>